openapi: 3.0.0
info:
  title: Textbook Personalization API
  description: API for textbook content personalization features
  version: 1.0.0
servers:
  - url: https://localhost:8000
    description: Local development server
paths:
  /api/personalize/{chapterId}:
    post:
      summary: Personalize textbook content for user
      description: Returns personalized content based on user profile and preferences
      parameters:
        - name: chapterId
          in: path
          required: true
          description: ID of the chapter to personalize
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                  description: ID of the authenticated user
                userProfile:
                  type: object
                  description: User profile with background and preferences
                  properties:
                    background:
                      type: string
                      description: User's software/hardware background
                    complexityPreference:
                      type: string
                      description: Preferred content complexity level
      responses:
        '200':
          description: Personalized content
          content:
            application/json:
              schema:
                type: object
                properties:
                  personalizedContent:
                    type: string
                    description: The personalized chapter content
                  originalContent:
                    type: string
                    description: The original chapter content for reference
        '400':
          description: Invalid request
        '401':
          description: Unauthorized access
