"""
Utility to check embedding dimensions and help troubleshoot vector dimension issues
"""

import sys
import os
sys.path.append(os.path.join(os.path.dirname(__file__), '..'))

from services.embedding_service import get_embeddings

def check_embedding_dimensions():
    """Check the dimensions of embeddings generated by the current model"""
    test_texts = ["This is a test sentence for checking embedding dimensions."]
    embeddings = get_embeddings(test_texts)
    
    if embeddings:
        dimensions = len(embeddings[0])
        print(f"Embedding dimensions: {dimensions}")
        return dimensions
    else:
        print("Failed to generate embeddings")
        return None

if __name__ == "__main__":
    check_embedding_dimensions()